In [52]:
import pandas as pd

In [54]:
df=pd.read_csv('./cardio_train.csv')
df['age'] = (df['age'] / 365.25).astype(int)

In [55]:
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,50,2,168,62,110,80,1,1,0,0,1,0
1,1,55,1,156,85,140,90,3,1,0,0,1,1
2,2,51,1,165,64,130,70,3,1,0,0,0,1
3,3,48,2,169,82,150,100,1,1,0,0,1,1
4,4,47,1,156,56,100,60,1,1,0,0,0,0

In [56]:
# df['age'] = (df['age'] / 365.25).astype(int)

In [57]:
df.shape[1] #column

13

In [58]:
df.shape[0] #row

70000

In [59]:
df.index

RangeIndex(start=0, stop=70000, step=1)

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  int64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: int64(13)
memory usage: 6.9 MB

In [61]:
df.tail()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
69995,99993,52,2,168,76,120,80,1,1,1,0,1,0
69996,99995,61,1,158,126,140,90,2,2,0,0,1,1
69997,99996,52,2,183,105,180,90,3,1,0,1,0,1
69998,99998,61,1,163,72,135,80,1,2,0,0,0,1
69999,99999,56,1,170,72,120,80,2,1,0,0,1,0

In [62]:
df.describe()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,49972.419900,52.803257,1.349571,164.359229,74.205543,128.817286,96.630414,1.366871,1.226457,0.088129,0.053771,0.803729,0.499700
std,28851.302323,6.762462,0.476838,8.210126,14.395829,154.011419,188.472530,0.680250,0.572270,0.283484,0.225568,0.397179,0.500003
min,0.000000,29.000000,1.000000,55.000000,10.000000,-150.000000,-70.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,25006.750000,48.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,50001.500000,53.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,74889.250000,58.000000,2.000000,170.000000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,99999.000000,64.000000,2.000000,250.000000,200.000000,16020.000000,11000.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

In [63]:
df.describe(include='all')

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,49972.419900,52.803257,1.349571,164.359229,74.205543,128.817286,96.630414,1.366871,1.226457,0.088129,0.053771,0.803729,0.499700
std,28851.302323,6.762462,0.476838,8.210126,14.395829,154.011419,188.472530,0.680250,0.572270,0.283484,0.225568,0.397179,0.500003
min,0.000000,29.000000,1.000000,55.000000,10.000000,-150.000000,-70.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,25006.750000,48.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,50001.500000,53.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,74889.250000,58.000000,2.000000,170.000000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,99999.000000,64.000000,2.000000,250.000000,200.000000,16020.000000,11000.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

In [64]:
df.columns

Index(['id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo',
       'cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio'],
      dtype='str')

In [65]:
df.dtypes

id             int64
age            int64
gender         int64
height         int64
weight         int64
ap_hi          int64
ap_lo          int64
cholesterol    int64
gluc           int64
smoke          int64
alco           int64
active         int64
cardio         int64
dtype: object

In [66]:
df.isnull().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [67]:
df.duplicated().sum()

np.int64(0)

In [68]:
df.nunique()

id             70000
age               28
gender             2
height           109
weight           155
ap_hi            153
ap_lo            157
cholesterol        3
gluc               3
smoke              2
alco               2
active             2
cardio             2
dtype: int64

In [69]:
df['gender'].unique()

array([2, 1])

In [70]:
df['smoke'].value_counts()

smoke
0    63831
1     6169
Name: count, dtype: int64

In [71]:
df.sample(5)

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
303,417,50,2,171,74,150,80,3,3,1,0,1,1
54195,77288,53,2,173,75,120,80,1,1,0,0,1,0
51506,73460,55,1,164,84,145,100,2,3,0,0,1,1
39416,56301,43,2,162,56,110,80,1,1,0,0,1,0
13615,19433,46,2,175,69,120,80,1,1,0,0,1,0

In [72]:
df.memory_usage()

Index             132
id             560000
age            560000
gender         560000
height         560000
weight         560000
ap_hi          560000
ap_lo          560000
cholesterol    560000
gluc           560000
smoke          560000
alco           560000
active         560000
cardio         560000
dtype: int64

In [73]:
df.corr(numeric_only=True)

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
id,1.000000,0.003836,0.003502,-0.003038,-0.001831,0.003356,-0.002529,0.006106,0.002467,-0.003699,0.001210,0.003755,0.003799
age,0.003836,1.000000,-0.022762,-0.081373,0.053565,0.020932,0.017553,0.153998,0.098529,-0.047479,-0.029674,-0.009803,0.237949
gender,0.003502,-0.022762,1.000000,0.499033,0.155412,0.006005,0.015254,-0.035821,-0.020491,0.338135,0.170966,0.005866,0.008109
height,-0.003038,-0.081373,0.499033,1.000000,0.290966,0.005488,0.006150,-0.050226,-0.018595,0.187989,0.094419,-0.006570,-0.010821
weight,-0.001831,0.053565,0.155412,0.290966,1.000000,0.030702,0.043711,0.141763,0.106859,0.067779,0.067115,-0.016865,0.181656
ap_hi,0.003356,0.020932,0.006005,0.005488,0.030702,1.000000,0.016086,0.023778,0.011841,-0.000922,0.001408,-0.000033,0.054475
ap_lo,-0.002529,0.017553,0.015254,0.006150,0.043711,0.016086,1.000000,0.024019,0.010806,0.005186,0.010601,0.004780,0.065719
cholesterol,0.006106,0.153998,-0.035821,-0.050226,0.141763,0.023778,0.024019,1.000000,0.451578,0.010354,0.035760,0.009911,0.221147
gluc,0.002467,0.098529,-0.020491,-0.018595,0.106859,0.011841,0.010806,0.451578,1.000000,-0.004756,0.011246,-0.006770,0.089307
smoke,-0.003699,-0.047479,0.338135,0.187989,0.067779,-0.000922,0.005186,0.010354,-0.004756,1.000000,0.340094,0.025858,-0.015486
alco,0.001210,-0.029674,0.170966,0.094419,0.067115,0.001408,0.010601,0.035760,0.011246,0.340094,1.000000,0.025476,-0.007330
active,0.003755,-0.009803,0.005866,-0.006570,-0.016865,-0.000033,0.004780,0.009911,-0.006770,0.025858,0.025476,1.000000,-0.035653
cardio,0.003799,0.237949,0.008109,-0.010821,0.181656,0.054475,0.065719,0.221147,0.089307,-0.015486,-0.007330,-0.035653,1.000000

In [74]:
df.sort_values(by='age')

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
30666,43842,29,1,159,59,120,80,1,1,0,0,1,0
22343,31922,29,2,175,92,100,60,1,1,0,0,1,0
6219,8850,29,1,175,59,120,80,1,1,0,0,1,0
55905,79749,30,1,160,59,110,70,1,1,0,0,1,0
32,44,39,1,159,60,110,70,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3326,4693,64,2,179,100,140,90,1,1,0,0,1,0
53413,76215,64,2,177,96,140,90,1,1,0,0,1,1
45829,65464,64,2,162,69,120,80,1,3,0,0,1,1
53294,76041,64,1,158,130,170,80,1,1,0,0,1,1
53285,76024,64,1,171,100,120,80,1,1,0,0,1,0

In [75]:
df.groupby('gender').mean(numeric_only=True)

,id,age,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
gender,,,,,,,,,,,,
1,49898.345267,52.916099,161.355612,72.565385,128.139249,94.522776,1.384735,1.235054,0.017856,0.025500,0.802021,0.496727
2,50110.246547,52.593298,169.947895,77.257295,130.078872,100.551982,1.333633,1.210462,0.218880,0.106375,0.806906,0.505231